### ISSUE TITLE
build errors on latest 4.2 alpha

### ISSUE THREAD

**Issue by morphoice** [chrismaltby/gb-studio#1761]
with my project wich worked on a previous 4.2 alpha version from a few weeks ago
I get the following compilation errors on the just newly released 4.2 alpha

...
Compiling: src/core/trigger.c 
Compiling: src/core/ui.c 
src/core/trigger.c:43: syntax error: token -> '*' ; column 46 
1 
Cancelled Build 

this happens after I ejected the engine
also some actors produce a relocation error before I did so.

however the sample project works fine so maybe it's a mistake on my end?

**Comment by morphoice** [comment]
I see. That might be it, it is indeed the Shmup Reloaded plugin, looks like there are a lot of changes to the engine, as I'm not very well versed in plugin coding or the c++ side in general, there's not much I can do. Is there some sort of documentation to that part of gbstudio? I noticed some keywords around bounding boxes have changed. bounding_box_t drops an error too, are they just renamed or isnt the solution that simple?
